const OtherProjectData=[
    {
        id: 1,
        title: "News App",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 2,
        title: "Password",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 1,
        title: "News App",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 2,
        title: "Password",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 1,
        title: "News App",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 2,
        title: "Password",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 1,
        title: "News App",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 2,
        title: "Password",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 1,
        title: "News App",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
      {
        id: 2,
        title: "Password",
        projectInfo: "lorem my name is shabbir anjum and your a great teacher",
        tools: "HTML, CSS, Javascript, React, Redux",
        src: "#",
      },
]
export default OtherProjectData;