const ExData = [
  {
    id: "smit",
    title: "Student developer At",
    link: "@",
    company: "SMIT",
    date: "Dec 2023 - present",
    src: "https://pk.worldorgs.com/catalog/faisalabad/accountant/saylani-mass-training-faisalabad",
    content: [
      "Learning advanced front-end development and backend programming.",
      "Enhancing skills in both domains.",
      "Working on cool projects to apply newly learned concepts.",
      "Improving problem-solving skills through hands-on experience.",
      "Participating in workshops and seminars to stay updated with industry trends.",
      "Collaborating with peers on group projects to enhance teamwork and communication skills.",
      "Engaging in coding challenges and hackathons to sharpen problem-solving abilities.",
      "Contributing to the development of internal tools or applications for practical learning.",
      "Networking with professionals and attending networking events to build connections in the industry.",
      "Exploring emerging technologies and frameworks to broaden technical knowledge.",
    ],
  },
  {
    id: "FIVER",
    title: "Front-End Developer At",
    link: "@",
    company: "Fiver",
    src: "https://www.fiverr.com/shabbir768?up_rollout=true",
    date: "SEP 2022 - present",
    content: [
      "Offering freelance web development services on Fiverr platform",
      "Communicating effectively with clients to understand project needs and provide timely updates",
      "Showcasing commitment and dedication to freelance work through active presence on Fiverr",
      "Continuously updating Fiverr profile with portfolio samples and client testimonials",
      "Offering personalized solutions and tailored services to meet client objectives",
      "Expanding skillset and exploring new technologies to offer innovative solutions to clients",
      'Offering additional services such as website maintenance, troubleshooting, and optimization'
    ],
  },
  {
    id: "GCUF",
    title: "Student developer At",
    link: "@",
    company: "GCUF",
    src: "https://gcuf.edu.pk/",
    date: "Aug 2019 - SEP 2023",
    content: ["Acquired a solid understanding of computer science principles and proficiency in various programming languages",
    "Demonstrated exceptional performance in web development courses, including HTML, CSS, and JavaScript",
    "Collaborated with classmates on projects to enhance teamwork and problem-solving skills",
    "Presented projects and assignments in front of faculty and peers to improve communication skills",
    "Contributed to organizing tech-related events or workshops within the university community",
    "Conducted research or independent projects on topics of interest within the field of computer science",],
  },
];
export default ExData;
